version: '2'

services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
  app:
    image: 'parkingppak:latest'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - spring.jpa.show-sql=true
      - elasticsearch.host=elasticsearch
      - elasticsearch.port=9200
      - spring.batch.initialize-schema=ALWAYS
      - api.elasticsearch.uri=http://elasticsearch:9200/
      - api.elasticsearch.search=_search

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres

#  jenkins:
#    image: jenkins/jenkins:latest
#    container_name: jenkins
#    ports:
#      - "8082:8080"
#      - "50000:50000"
#    volumes:
#      - jenkins:/var/jenkins_home

  elasticsearch:
    container_name: elasticsearch
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      - node.name=elasticsearch
      - cluster.name=elasticsearch
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
#  kibana:
#    image: docker.elastic.co/kibana/kibana:7.12.0
#    container_name: kibana
#    environment:
#      - ELASTICSEARCH_URL=http://elasticsearch:9200
#      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
#    ports:
#      - 5601:5601
#    depends_on:
#      - elasticsearch
volumes:
  esdata:
#  jenkins:
